=== Zoomicon/tranXform/src/VBFormDesignToXML/VBFormDesign.dtd
<!-- 
Description: VB Form Design info
Author: George Birbilis (birbilis@kagi.com)
Version: 10Dec2002
-->

<!ELEMENT VBFORM (VERSION,OBJECT*,COMPONENT,ATTRIBUTE*)>
 <!ELEMENT VERSION (#PCDATA)>
 
 <!ELEMENT OBJECT (GUID,VER,FILENAME)>
  <!ELEMENT GUID (#PCDATA)>
  <!ELEMENT VER (#PCDATA)>
  <!ELEMENT FILENAME (#PCDATA)>

 <!ELEMENT PROPERTY (NAME,VALUE?,PROPERTY*)>
  <!ELEMENT NAME (#PCDATA)>
  <!ELEMENT VALUE (#PCDATA)>

 <!ELEMENT EVENT (NAME,HANDLERNAME)>
  <!ELEMENT HANDLERNAME (#PCDATA)>

 <!ELEMENT EVENTS (EVENT*)>

 <!ELEMENT COMPONENT (CLASS,NAME,PROPERTY*,EVENTS?,COMPONENT*)>

 <!ELEMENT ATTRIBUTE (NAME,VALUE)>
 <!ELEMENT CLASS (#PCDATA)>

=== Zoomicon/tranXform/src/VBFormDesignToXML/building.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE VBFORM SYSTEM "VBFormDesign.dtd" []>

<!--
 VB form design info generated using the VBFormDesignToXML
 tool which is (C)2002-2004 G.Birbilis (birbilis@kagi.com)
-->

<VBFORM>
 <VERSION>5.00</VERSION>
  <OBJECT>
   <GUID>67397AA1-7FB1-11D0-B148-00A0C922E820</GUID>
   <VER>#6.0#0</VER>
   <FILENAME></FILENAME>
  </OBJECT>
  <OBJECT>
   <GUID>F0D2F211-CCB0-11D0-A316-00AA00688B10</GUID>
   <VER>#1.0#0</VER>
   <FILENAME></FILENAME>
  </OBJECT>
  <OBJECT>
   <GUID>BDC217C8-ED16-11CD-956C-0000C04E4C0A</GUID>
   <VER>#1.1#0</VER>
   <FILENAME></FILENAME>
  </OBJECT>
  <OBJECT>
   <GUID>97BD7A06-77E0-11D2-8EAE-008048E27A77</GUID>
   <VER>#1.0#0</VER>
   <FILENAME></FILENAME>
  </OBJECT>
 <COMPONENT>
  <CLASS>VB.Form</CLASS>
  <NAME>building</NAME>
   <PROPERTY>
    <NAME>BorderStyle</NAME>
    <VALUE>3</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>Caption</NAME>
    <VALUE>Κτίρια (Α.11 - Α.19)</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>ClientHeight</NAME>
    <VALUE>8028</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>ClientLeft</NAME>
    <VALUE>600</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>ClientTop</NAME>
    <VALUE>468</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>ClientWidth</NAME>
    <VALUE>10212</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>Font</NAME>
   <PROPERTY>
    <NAME>Name</NAME>
    <VALUE>Arial</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>Size</NAME>
    <VALUE>8.4</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>Charset</NAME>
    <VALUE>161</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>Weight</NAME>
    <VALUE>700</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>Underline</NAME>
    <VALUE>0</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>Italic</NAME>
    <VALUE>0</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>Strikethrough</NAME>
    <VALUE>0</VALUE>
   </PROPERTY>
   </PROPERTY>
   <PROPERTY>
    <NAME>KeyPreview</NAME>
    <VALUE>-1</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>LinkTopic</NAME>
    <VALUE>Form1</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>MaxButton</NAME>
    <VALUE>0</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>MinButton</NAME>
    <VALUE>0</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>ScaleHeight</NAME>
    <VALUE>8028</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>ScaleWidth</NAME>
    <VALUE>10212</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>ShowInTaskbar</NAME>
    <VALUE>0</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>StartUpPosition</NAME>
    <VALUE>2</VALUE>
   </PROPERTY>
 <COMPONENT>
  <CLASS>VB.CommandButton</CLASS>
  <NAME>btnCancel</NAME>
   <PROPERTY>
    <NAME>Caption</NAME>
    <VALUE>Ακύρωση και επιστροφή</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>Font</NAME>
   <PROPERTY>
    <NAME>Name</NAME>
    <VALUE>Arial</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>Size</NAME>
    <VALUE>8.4</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>Charset</NAME>
    <VALUE>161</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>Weight</NAME>
    <VALUE>400</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>Underline</NAME>
    <VALUE>0</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>Italic</NAME>
    <VALUE>0</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>Strikethrough</NAME>
    <VALUE>0</VALUE>
   </PROPERTY>
   </PROPERTY>
   <PROPERTY>
    <NAME>Height</NAME>
    <VALUE>375</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>Left</NAME>
    <VALUE>5160</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>TabIndex</NAME>
    <VALUE>34</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>Top</NAME>
    <VALUE>7560</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>Width</NAME>
    <VALUE>2295</VALUE>
   </PROPERTY>
    <EVENTS>
    <EVENT>
     <NAME>Click</NAME>
     <HANDLERNAME>btnCancel_Click</HANDLERNAME>
    </EVENT>
    </EVENTS>
 </COMPONENT>
 <COMPONENT>
  <CLASS>VB.CommandButton</CLASS>
  <NAME>btnSubmit</NAME>
   <PROPERTY>
    <NAME>Caption</NAME>
    <VALUE>Καταχώρηση και επιστροφή</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>Font</NAME>
   <PROPERTY>
    <NAME>Name</NAME>
    <VALUE>MS Sans Serif</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>Size</NAME>
    <VALUE>7.8</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>Charset</NAME>
    <VALUE>161</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>Weight</NAME>
    <VALUE>400</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>Underline</NAME>
    <VALUE>0</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>Italic</NAME>
    <VALUE>0</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>Strikethrough</NAME>
    <VALUE>0</VALUE>
   </PROPERTY>
   </PROPERTY>
   <PROPERTY>
    <NAME>Height</NAME>
    <VALUE>375</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>Left</NAME>
    <VALUE>2400</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>TabIndex</NAME>
    <VALUE>33</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>Top</NAME>
    <VALUE>7560</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>Width</NAME>
    <VALUE>2295</VALUE>
   </PROPERTY>
    <EVENTS>
    <EVENT>
     <NAME>Click</NAME>
     <HANDLERNAME>btnSubmit_Click</HANDLERNAME>
    </EVENT>
    </EVENTS>
 </COMPONENT>
 <COMPONENT>
  <CLASS>VB.CommandButton</CLASS>
  <NAME>btnDelete</NAME>
   <PROPERTY>
    <NAME>Caption</NAME>
    <VALUE>Διαγραφή κτιρίου</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>Font</NAME>
   <PROPERTY>
    <NAME>Name</NAME>
    <VALUE>MS Sans Serif</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>Size</NAME>
    <VALUE>7.8</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>Charset</NAME>
    <VALUE>161</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>Weight</NAME>
    <VALUE>400</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>Underline</NAME>
    <VALUE>0</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>Italic</NAME>
    <VALUE>0</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>Strikethrough</NAME>
    <VALUE>0</VALUE>
   </PROPERTY>
   </PROPERTY>
   <PROPERTY>
    <NAME>Height</NAME>
    <VALUE>375</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>Left</NAME>
    <VALUE>6360</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>TabIndex</NAME>
    <VALUE>32</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>Top</NAME>
    <VALUE>7080</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>Width</NAME>
    <VALUE>1935</VALUE>
   </PROPERTY>
    <EVENTS>
    <EVENT>
     <NAME>Click</NAME>
     <HANDLERNAME>btnDelete_Click</HANDLERNAME>
    </EVENT>
    </EVENTS>
 </COMPONENT>
 <COMPONENT>
  <CLASS>VB.CommandButton</CLASS>
  <NAME>btnAdd</NAME>
   <PROPERTY>
    <NAME>Caption</NAME>
    <VALUE>Εισαγωγή νέου κτιρίου</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>Font</NAME>
   <PROPERTY>
    <NAME>Name</NAME>
    <VALUE>MS Sans Serif</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>Size</NAME>
    <VALUE>7.8</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>Charset</NAME>
    <VALUE>161</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>Weight</NAME>
    <VALUE>400</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>Underline</NAME>
    <VALUE>0</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>Italic</NAME>
    <VALUE>0</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>Strikethrough</NAME>
    <VALUE>0</VALUE>
   </PROPERTY>
   </PROPERTY>
   <PROPERTY>
    <NAME>Height</NAME>
    <VALUE>375</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>Left</NAME>
    <VALUE>4080</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>TabIndex</NAME>
    <VALUE>31</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>Top</NAME>
    <VALUE>7080</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>Width</NAME>
    <VALUE>2055</VALUE>
   </PROPERTY>
    <EVENTS>
    <EVENT>
     <NAME>Click</NAME>
     <HANDLERNAME>btnAdd_Click</HANDLERNAME>
    </EVENT>
    </EVENTS>
 </COMPONENT>
 <COMPONENT>
  <CLASS>TabDlg.SSTab</CLASS>
  <NAME>tabA17A19</NAME>
   <PROPERTY>
    <NAME>Height</NAME>
    <VALUE>3492</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>Left</NAME>
    <VALUE>120</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>TabIndex</NAME>
    <VALUE>26</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>Top</NAME>
    <VALUE>3480</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>Width</NAME>
    <VALUE>9972</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>_ExtentX</NAME>
    <VALUE>17590</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>_ExtentY</NAME>
    <VALUE>6160</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>_Version</NAME>
    <VALUE>393216</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>Tabs</NAME>
    <VALUE>2</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>TabHeight</NAME>
    <VALUE>882</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>Font</NAME>
   <PROPERTY>
    <NAME>Name</NAME>
    <VALUE>Arial</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>Size</NAME>
    <VALUE>8.4</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>Charset</NAME>
    <VALUE>161</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>Weight</NAME>
    <VALUE>400</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>Underline</NAME>
    <VALUE>0</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>Italic</NAME>
    <VALUE>0</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>Strikethrough</NAME>
    <VALUE>0</VALUE>
   </PROPERTY>
   </PROPERTY>
   <PROPERTY>
    <NAME>TabCaption(0)</NAME>
    <VALUE>Α.17. Ποιά είναι η κατάσταση του κτιρίου;</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>TabPicture(0)</NAME>
    <VALUE>building.frx":000</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>Tab(0).ControlEnabled</NAME>
    <VALUE>-1</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>Tab(0).Control(0)</NAME>
    <VALUE>dgA17</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>Tab(0).Control(0).Enabled</NAME>
    <VALUE>0</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>Tab(0).Control(1)</NAME>
    <VALUE>btnA17a</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>Tab(0).Control(1).Enabled</NAME>
    <VALUE>0</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>Tab(0).ControlCount</NAME>
    <VALUE>2</VALUE>
   </PROPERTY>
   <PROPERTY>
    <NAME>TabCaption(1)</NAME>
    <VALUE>Α.19. Πότε προβλέπεται συντήρηση του κτιρίου και σε ποιόν τομέα;</VALUE>
   </PROPERTY>
   <PROPERTY>
